FROM plugins/base:windows-ltsc2022-amd64

USER ContainerAdministrator

ENV GODEBUG=netdns=go

ADD scripts/download_detect.ps1 C:/download_detect.ps1

RUN powershell -File C:/download_detect.ps1

ADD release/windows/amd64/synopsys-detect.exe C:/synopsys-detect.exe

ENTRYPOINT ["C:\\synopsys-detect.exe"]